name: Push actions

on:
  push:
    branches:
      - master
      - dev
      - main

jobs:
  validatehassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v3.5.2"

        - name: "Run hassfest validation"
          uses: "home-assistant/actions/hassfest@master"

  validatehacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v3.5.2"

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
            # ignore: "brands"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v2"
        - uses: "actions/setup-python@v1"
          with:
            python-version: "3.x"
        - run: python3 -m pip install black
        - run: black .